### ISSUE TITLE
Software deployment

### ISSUE THREAD

**Issue by Alexander-Dubrawski** [hyrise/Cockpit#535]
**Is your feature request related to a problem? Please describe:**  
The client requested to be able to easily install the cockpit and use it straight away. 

**Please describe the solution you'd like:**  
After I little research I found two approaches that we can use. 

**Docker** 
We already have a docker set up for deploying the Software. I would suggest simplifying and automate it a little bit more. 
 
1. I think three images should be sufficient. One that starts all the backend-components inside, one that starts the frontend and one that starts the influx. In #524 I already implemented a script that can start all the backend components. Or we could simply just start multiple entry points (https://stackoverflow.com/questions/18805073/docker-multiple-entrypoints).
2. We could build and push the images with GitHub action. So every time we merge into dev we build an up to date image. The docker-compose file could then just simply use these images. Moreover, we wouldn't need to mount the working directory.  

*We could update our git hub action as follows:*

```yml
on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps: 

   ...

    - uses: actions/checkout@v2
    - name: Build the backend docker image and push it
       run: 
          docker build . --tag cockpit/backend:$(date +%s)
          docker login --username foo --password $({ secrets.GITHUB_TOKEN })
          docker push  cockpit/backend:$(date +%s)

   ...

```

We could also push the images to GitHub packages (https://github.com/features/packages).

In this solution, the user just needs to work with the docker-compose file. 

I think this set-up should run fine on a Linux machine and on a slightly more powerful mac. 

**Using a process manager**  
Besides of docker, we can provide a direct installation. This could improve the performance on Mac.  For that, we can provide a shell script that installs all dependencies for Mac or Linux. To start the components we can use a Process manager like: 

https://github.com/DarthSim/overmind

or 

https://github.com/ddollar/foreman
